# Generated by Django 4.1.2 on 2022-10-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_product_payment_orderitem_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
    ]
